[tool.poetry]
name = "telemetry-adapter"
version = "0.1.0"
description = ""
authors = ["Andrey Arakelyants"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "1.34"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
